cask "font-fira-code-nerd-font"

brew "astro"
brew "bat"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "lazydocker"
brew "lazygit"
brew "starship"
brew "uv"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
