format = """
$directory\
$package\
$git_branch\
$git_status\
$git_metrics\
$fill\
$python\
$cmd_duration\
$line_break\
$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
surface0 = "#313244"
surface1 = "#45475a"
overlay1 = "#7f849c"
text = "#cdd6f4"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
mauve = "#cba6f7"
pink = "#f5c2e7"
peach = "#fab387"
teal = "#94e2d5"
sky = "#89dceb"
lavender = "#b4befe"
rosewater = "#f5e0dc"

[character]
error_symbol = "[❯](bold mauve)"
success_symbol = "[❯](bold mauve)"

[fill]
symbol = "  "

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"
format = '[$path ]($style)'

[package]
format = "[$version]($style) "
style = "sky"

[git_branch]
style = "bold pink"
format = "on [$branch(:$remote_branch)]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[git_metrics]
disabled = false

[python]
format = '[(\($virtualenv\) )]($style)'
